const mongoose = require('mongoose');

// Define Company Schema
const companySchema = new mongoose.Schema({
        _id: {
            type: mongoose.Schema.Types.ObjectId,
            auto: true, // Automatically generated by MongoDB
        },
    name: {
        type: String,
        required: true,
    },
    mobile: {
        type: String,
        required: true,
        unique: true,
    },
    address: {
        type: String,
    },
    key15: {
        type: String,
        unique: true,
    },
    key1month: {
        type: String,
        unique: true,
    },
    key1year: {
        type: String,
        unique: true,
    },
    // Additional fields can be added here
});

// Create Company model
const Company = mongoose.model('Company', companySchema);

module.exports = Company;