// const mongoose = require('mongoose');

// const TokenSchema = new mongoose.Schema({
//     companyName: String,
//     mobileNumber: String,
//     validity: String,
//     jwtToken: String,
//     createdAt: { type: Date, default: Date.now },
//     status: { type: String, default: 'active' }
// });

// const Token = mongoose.model('Token', TokenSchema);

const mongoose = require('mongoose');

const TokenSchema = new mongoose.Schema({
    _id: {
        type: mongoose.Schema.Types.ObjectId,
        auto: true, // Automatically generated by MongoDB
    },
    companyName: {
        type: String,
        // required: true
    },
    mobileNumber: {
        type: String,
        // required: true
    },
    validity: {
        type: String,
        required: true
    },
    jwtToken: {
        type: String,
        required: true
    },
    status: {
        type: String,
        default: 'active'
    },
    createdAt: {
        type: Date,
        default: Date.now
    },
    startDate: {
        type: Date,
    },
    endDate: {
        type: Date,
        default: null,
    },
    daysRemaining: {
        type: String,
    },
});

const Token = mongoose.model('Token', TokenSchema);

module.exports = Token;
